// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlhY78jXwjcdT-IvPmLqo684dXgiIeXjE',
    appId: '1:549717601795:web:c06be789c2f57541fc6836',
    messagingSenderId: '549717601795',
    projectId: 'biomechai',
    authDomain: 'biomechai.firebaseapp.com',
    storageBucket: 'biomechai.firebasestorage.app',
    measurementId: 'G-C1WY3E6C0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPc5f827tB-SgYVvbUVVO4DqAl5aW-Ufo',
    appId: '1:549717601795:android:0a310684258003b9fc6836',
    messagingSenderId: '549717601795',
    projectId: 'biomechai',
    storageBucket: 'biomechai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMiUMuuf13XChKv_ze-gRW1CtFMdAMuEk',
    appId: '1:549717601795:ios:f485fe28143b1802fc6836',
    messagingSenderId: '549717601795',
    projectId: 'biomechai',
    storageBucket: 'biomechai.firebasestorage.app',
    iosBundleId: 'com.example.biomechai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMiUMuuf13XChKv_ze-gRW1CtFMdAMuEk',
    appId: '1:549717601795:ios:f485fe28143b1802fc6836',
    messagingSenderId: '549717601795',
    projectId: 'biomechai',
    storageBucket: 'biomechai.firebasestorage.app',
    iosBundleId: 'com.example.biomechai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlhY78jXwjcdT-IvPmLqo684dXgiIeXjE',
    appId: '1:549717601795:web:22cf33287f82415bfc6836',
    messagingSenderId: '549717601795',
    projectId: 'biomechai',
    authDomain: 'biomechai.firebaseapp.com',
    storageBucket: 'biomechai.firebasestorage.app',
    measurementId: 'G-KJXRWXWB2P',
  );
}
